# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Gestor de paquetes del proyecto
  - package-ecosystem: "maven"
    # Location of package manifests
    directory: "/"
    schedule:
      # Intervalo para la busqueda de nuevas versiones de librerias
      interval: "weekly" 
      # Dia de la semana en la que buscará las nuevas versiones de librerias
      day: "sunday"
    # Usuario asignado (Pendiente de analizar esta propiedad)   
    assignees:
    - "Jose Carlos Serrano Catena"
    # Permite que dependabot pueda tener hasta un maximo de 10 pull request abiertas 
    open-pull-requests-limit: 10
    # Rama contra la que realizara el pull request
    target-branch: "master"
