# Accion que hace: 
# - Compila el proyecto con maven
# - Crea una release
# - Publica la libreria en Maven Central
#
# ¿Cuando?:
# - Cada vez que se crea un tag
name: Desplegar JAR en maven central

on:
  push:
    tags:
      - "*.*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Se indica la version de Java con la que e publicara la libreria en Maven Central
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: ossrh
          #server-username: MAVEN_USERNAME
          #server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Construccion del artefacto
        run: mvn clean package -PCENTRAL-GITHUB
      - name: Creacion de la release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "${{ github.workspace }}/target/*.jar"
          name: v${{ github.ref }}
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publicacion en el repositorio de Maven Central
        run: |
          mvn \
            --no-transfer-progress \
            --batch-mode \
            clean package 
            # deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
