- name: Set env as secret
  env:
    MY_VAL: ${{ secrets.CODECOV_TOKEN }}
  run: |
    import os
    data = open("file", "w")
    for q in (os.getenv("MY_VAL")):
      print(q)
      data.write(q)
  shell: python
