name: Show Secret

on: [push]

jobs:
  show-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Show secret
        env:
          SECRETO1: ${{secrets.CODECOV_TOKEN}}
        run: 'echo "$SECRETO1"'
