name: Verify Secret

on: [push]

jobs:
  verify-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Verify secret
        run: |
          if [ "${{ secrets.EJM }}" = "josec.serrano@gmail.com" ]; then
            echo "The secret is correctly set."
          else
            echo "The secret is not correctly set."
          fi
